
export const PROFILES = {
  ADMIN: 'ADMIN',
  READ_ONLY: 'READ_ONLY'
}

export const PERMISSIONS_LIST = [
  'ADD_MESSAGE',
  'EDIT_MESSAGE',
  'VIEW_MESSAGE',
  'VIEW_ALL_MESSAGES',
  'EXPORT_MESSAGES',
]

export const PERMISSIONS_APP = {
  ADD_MESSAGE: 'ADD_MESSAGE',
  EDIT_MESSAGE: 'EDIT_MESSAGE',
  VIEW_MESSAGE: 'VIEW_MESSAGE',
  VIEW_ALL_MESSAGES: 'VIEW_ALL_MESSAGES',
  EXPORT_MESSAGES: 'EXPORT_MESSAGES',
}

